// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using praktyki_backend.Models;

#nullable disable

namespace praktyki_backend.Migrations
{
    [DbContext(typeof(dbcontext))]
    partial class dbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("praktyki_backend.Models.Cardenablers", b =>
                {
                    b.Property<int>("Cards_Enablers_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cards_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Enablers_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cards_Enablers_Id");

                    b.HasIndex("Cards_Id");

                    b.ToTable("Cardenablers");
                });

            modelBuilder.Entity("praktyki_backend.Models.Cards", b =>
                {
                    b.Property<int>("Cards_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Card_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cards_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("praktyki_backend.Models.Cardweights", b =>
                {
                    b.Property<int>("Cards_Weights_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cards_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Processes_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weights_X")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weights_Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cards_Weights_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Processes_Id");

                    b.ToTable("Cardweights");
                });

            modelBuilder.Entity("praktyki_backend.Models.Decisions", b =>
                {
                    b.Property<int>("Decisions_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cards_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Decisions_Cost_Bits")
                        .HasColumnType("REAL");

                    b.Property<int>("Decisions_Cost_Bits_Weight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decisions_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Decisions_Short_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Decisions_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("praktyki_backend.Models.Decks", b =>
                {
                    b.Property<int>("Decks_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deck_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Users_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Decks_Id");

                    b.HasIndex("Users_Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Feedbacks", b =>
                {
                    b.Property<int>("Feedbacks_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cards_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Feedbacks_Long_Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Feedbacks_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Gameevents", b =>
                {
                    b.Property<int>("Games_Events_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Boosters_X")
                        .HasColumnType("REAL");

                    b.Property<double?>("Boosters_Y")
                        .HasColumnType("REAL");

                    b.Property<double?>("Decisions_Cost_Bits_Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Events_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Events_Short_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Hardware_Cost_Bits_Weight")
                        .HasColumnType("REAL");

                    b.Property<double?>("Software_Cost_Bits_Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("Turns_Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Games_Events_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Gameevents");
                });

            modelBuilder.Entity("praktyki_backend.Models.GamemasterRequest", b =>
                {
                    b.Property<int>("Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Request_Id");

                    b.ToTable("GamemasterRequests");
                });

            modelBuilder.Entity("praktyki_backend.Models.Hardwares", b =>
                {
                    b.Property<int>("Hardwares_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cards_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hardwares_Cost_Bits")
                        .HasColumnType("REAL");

                    b.Property<int>("Hardwares_Cost_Bits_Weight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hardwares_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hardwares_Short_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Hardwares_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("praktyki_backend.Models.Processes", b =>
                {
                    b.Property<int>("Processes_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Processes_Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Processes_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Processes_Desc_Long")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Processes_Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Processes_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("praktyki_backend.Models.Softwares", b =>
                {
                    b.Property<int>("Softwares_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cards_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decks_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Softwares_Cost_Bits")
                        .HasColumnType("REAL");

                    b.Property<int>("Softwares_Cost_Bits_Weight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Softwares_Long_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Softwares_Short_Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Softwares_Id");

                    b.HasIndex("Cards_Id");

                    b.HasIndex("Decks_Id");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("praktyki_backend.Models.Users", b =>
                {
                    b.Property<int>("Users_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Users_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("praktyki_backend.Models.Cardenablers", b =>
                {
                    b.HasOne("praktyki_backend.Models.Cards", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("praktyki_backend.Models.Cards", b =>
                {
                    b.HasOne("praktyki_backend.Models.Decks", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Cardweights", b =>
                {
                    b.HasOne("praktyki_backend.Models.Cards", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("praktyki_backend.Models.Processes", "Processes")
                        .WithMany()
                        .HasForeignKey("Processes_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");

                    b.Navigation("Processes");
                });

            modelBuilder.Entity("praktyki_backend.Models.Decisions", b =>
                {
                    b.HasOne("praktyki_backend.Models.Cards", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("praktyki_backend.Models.Decks", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");

                    b.Navigation("Decks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Decks", b =>
                {
                    b.HasOne("praktyki_backend.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("Users_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("praktyki_backend.Models.Feedbacks", b =>
                {
                    b.HasOne("praktyki_backend.Models.Cards", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("praktyki_backend.Models.Decks", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");

                    b.Navigation("Decks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Gameevents", b =>
                {
                    b.HasOne("praktyki_backend.Models.Decks", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Hardwares", b =>
                {
                    b.HasOne("praktyki_backend.Models.Cards", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("praktyki_backend.Models.Decks", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");

                    b.Navigation("Decks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Processes", b =>
                {
                    b.HasOne("praktyki_backend.Models.Decks", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decks");
                });

            modelBuilder.Entity("praktyki_backend.Models.Softwares", b =>
                {
                    b.HasOne("praktyki_backend.Models.Cards", "Cards")
                        .WithMany()
                        .HasForeignKey("Cards_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("praktyki_backend.Models.Decks", "Decks")
                        .WithMany()
                        .HasForeignKey("Decks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cards");

                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
